-- CreateTable
CREATE TABLE "single_coin_data" (
    "id" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "web_slug" TEXT,
    "asset_platform_id" TEXT,
    "platforms" JSONB,
    "detail_platforms" JSONB,
    "block_time_in_minutes" INTEGER,
    "hashing_algorithm" TEXT,
    "categories" TEXT[],
    "preview_listing" BOOLEAN,
    "public_notice" TEXT,
    "additional_notices" TEXT[],
    "localization" JSONB NOT NULL,
    "description" JSONB NOT NULL,
    "links" JSONB NOT NULL,
    "image" JSONB NOT NULL,
    "country_origin" TEXT,
    "genesis_date" TIMESTAMP(3),
    "sentiment_votes_up_percentage" DOUBLE PRECISION,
    "sentiment_votes_down_percentage" DOUBLE PRECISION,
    "market_cap_rank" INTEGER,
    "market_data" JSONB,
    "public_interest_stats" JSONB,
    "last_updated" TIMESTAMP(3) NOT NULL,
    "status_updates" JSONB,
    "tickers" JSONB,
    "createdAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(6) NOT NULL,

    CONSTRAINT "single_coin_data_pkey" PRIMARY KEY ("id")
);
