export const marketDataSchema = {
  type: 'array',
  items: {
    type: 'object',
    properties: {
      id: { type: 'string' },
      symbol: { type: 'string' },
      name: { type: 'string' },
      image: { type: 'string' },
      current_price: { type: 'number' },
      market_cap: { type: ['number', 'null'] },
      market_cap_rank: { type: 'integer' },
      fully_diluted_valuation: { type: ['number', 'null'] },
      total_volume: { type: ['number', 'null'] },
      high_24h: { type: ['number', 'null'] },
      low_24h: { type: ['number', 'null'] },
      price_change_24h: { type: ['number', 'null'] },
      price_change_percentage_24h: { type: ['number', 'null'] },
      market_cap_change_24h: { type: ['number', 'null'] },
      market_cap_change_percentage_24h: { type: ['number', 'null'] },
      circulating_supply: { type: ['number', 'null'] },
      total_supply: { type: ['number', 'null'] },
      max_supply: { type: ['number', 'null'] },
      ath: { type: ['number', 'null'] },
      ath_change_percentage: { type: ['number', 'null'] },
      ath_date: { type: 'string' },
      atl: { type: ['number', 'null'] },
      atl_change_percentage: { type: ['number', 'null'] },
      atl_date: { type: 'string' },
      last_updated: { type: 'string' },
      sparkline_in_7d: {
        type: 'array',
        items: { type: 'number' },
      },
    },
    required: [
      'id',
      'symbol',
      'name',
      'image',
      'current_price',
      'market_cap',
      'market_cap_rank',
      'total_volume',
      'high_24h',
      'low_24h',
      'price_change_24h',
      'price_change_percentage_24h',
      'market_cap_change_24h',
      'market_cap_change_percentage_24h',
      'circulating_supply',
      'total_supply',
      'max_supply',
      'ath',
      'ath_change_percentage',
      // 'ath_date',
      'atl',
      'atl_change_percentage',
      // 'atl_date',
      // 'last_updated',
      'sparkline_in_7d',
    ],
  },
};
